config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'trainings#index'
  get '/training/new', to: 'trainings#new'

  resources :trainings
  resources :calories
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calory.rb
class Calory < ApplicationRecord
  belongs_to :user
  with_options presence: true do
    validates :calories_intake, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10_000 }
    validates :start_time
  end
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :training_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角文字を使用してください' }
    validates :weight, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 300 }
    validates :number, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
    validates :start_time
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :body_weight, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 300 }
    validates :height, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 300 }
  end

  has_many :trainings, dependent: :destroy
  has_many :calories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :body_weight, :height])
  end
end

app/controllers/calories_controller.rb
class CaloriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @calories = Calory.all
    @calory = Calory.new
  end

  def new
    @calory = Calory.new
  end

  def show
    @calory = Calory.find(params[:id])
  end

  def create
    @calory = Calory.new(calory_parameter)
    if @calory.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @calory = Calory.find(params[:id])
    @calory.destroy
    redirect_to root_path
  end

  def edit
    @calory = Calory.find(params[:id])
  end

  def update
    @calory = Calory.find(params[:id])
    if @calory.update(calory_parameter)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

  def calory_parameter
    params.require(:calory).permit(:calories_intake, :start_time).merge(user_id: current_user.id)
  end

  def move_to_index
    return if user_signed_in?

    redirect_to action: :index
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @trainings = Training.all
    @training = Training.new
    @calories = Calory.all
  end

  def new
    @training = Training.new
  end

  def show
    @training = Training.find(params[:id])
  end

  def create
    @training = Training.new(training_parameter)
    if @training.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @training = Training.find(params[:id])
    @training.destroy
    redirect_to trainings_path, notice: '削除しました'
  end

  def edit
    @training = Training.find(params[:id])
  end

  def update
    @training = Training.find(params[:id])
    if @training.update(training_parameter)
      redirect_to trainings_path, notice: '編集しました'
    else
      render 'edit'
    end
  end

  private

  def training_parameter
    params.require(:training).permit(:training_name, :weight, :number, :start_time).merge(user_id: current_user.id)
  end

  def move_to_index
    return if user_signed_in?

    redirect_to action: :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @nickname = current_user.nickname
    @trainings = current_user.trainings
  end

  def edit
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to edit_user_path, notice: '編集しました'
    else
      render 'edit'
    end
  end

  def update
    current_user.update(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :body_weight, :height)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def render_day(day, trainings, calories)
    render_trainings(day, trainings) + render_calories(day, calories)
  end

  private

  def render_trainings(day, trainings)
    trainings_on_day = trainings.select { |training| training.start_time.to_date == day }
    trainings_on_day.map { |training| content_tag(:div, link_to(training.training_name, training)) }.join.html_safe
  end

  def render_calories(day, calories)
    calories_on_day = calories.select { |calory| calory.start_time.to_date == day }
    calories_on_day.map { |calory| content_tag(:div, link_to(calory.calories_intake, calory)) }.join.html_safe
  end
end

app/helpers/calories_helper.rb
module CaloriesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calories/edit.html.erb
<%= render "shared/first_header" %>
<%= render "shared/header" %>

<h2>摂取カロリー量を編集する</h2>

<%= form_with(model: @calory, local: true) do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  
  <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">摂取カロリー量</label>
    <%= f.text_field :calories_intake, class: "form-control", id: "exampleFormControlInput1" %> <span>kcal</span>
  </div>

  <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">日付</label>
    <%= f.datetime_select :start_time, class: "form-control", id: "exampleFormControlInput1" %> 
  </div>

  <div class="d-grid gap-2">
  <%= f.submit "更新する", class: "btn btn-primary" %>
  <%= link_to "戻る", :back, class: "btn btn-primary"%>
  </div>
  <% end %>
  
  <%= render "shared/footer" %>

app/views/calories/new.html.erb
<%= render "shared/first_header" %>
<%= render "shared/header" %>

<div class="calory-main">
    <h2 class="calory_content">接種カロリー量を記録</h2>
    <%= form_with(model: @calory, local: true) do |f| %>

      <%= render 'shared/error_messages', model: f.object %>

      <div class="mb-3">
     <label for="exampleFormControlInput1" class="form-label">*必須* 摂取カロリー量</label>
      <%= f.text_field :calories_intake, class: "form-control", id: "exampleFormControlInput1" %>
      <span>kcal</script>
      </div>
      
      <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">日付</label>
      <div>
     <%= f.datetime_select :start_time, class: "form-control", id: "exampleFormControlInput1" %>
     </div>
     </div>
     
     <div class="d-grid gap-2">
     <%= f.submit "記録する", class: "btn btn-primary" %>
     <%= link_to '戻る', root_path, class: "btn btn-primary" %>
   </div>
 <% end %>
</div>

<%= render "shared/footer" %>

    

app/views/calories/show.html.erb
<%= render "shared/first_header" %>
<%= render "shared/header" %>

<h2>摂取カロリー</h2>

<table class="table">
  <thead>
 
  </thead>
  <tbody>
    <tr>
      <td>摂取カロリー量</td>
      <td>  <%= @calory.calories_intake %>
      <span>kcal</script></td>
    </tr>

    <td>日付</td>
    <td><%= @calory.start_time.strftime("%m-%d") %></td>
  </tr>


  </tbody>
</table>



<div class="d-grid gap-2">
<%= link_to '編集', edit_calory_path(@calory), class: "btn btn-primary" %>
<%= link_to '消去', calory_path(@calory.id), class: "btn btn-primary", method: :delete, data: { confirm: '本当に?' } %>
<%= link_to '戻る', root_path, class: "btn btn-primary" %>
</div>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trainer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </head>

  <body>
  <div class="container">
    <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_first_header.html.erb
<div class="title">
  <h1 class="display-1">
  Trainer
  </h1>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
<h4>
<%= link_to 'TOP', root_path, class: "font" %>
</h4>
</div>

app/views/shared/_header.html.erb
     <% if user_signed_in? %>
     <nav class="navbar navbar-light bg-light">
     <div class="container-fluid">
      <%= link_to current_user.nickname, user_path(current_user), class: "navbar-brand" %>
      </div>
    </nav>
    <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "navbar-brand" %> 
      </div>
      </nav>
    <% else %>
    <nav class="navbar navbar-light bg-light">
     <div class="container-fluid">
      <%= link_to 'Login', new_user_session_path, class: "navbar-brand" %>
      </div>
      </nav>
      <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
      <%= link_to '新規登録', new_user_registration_path, class: "navbar-brand" %>
      </div>
      </nav>
    <% end %>
    

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <% date = day.to_date %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <%= date.day %>
              <div>トレーニング/</div>
              <div>摂取カロリー量(kcal)</div>
              <hr width="100" size="100" >

              <%= render_day(day, @trainings.select { |training| training.user_id == current_user.id }, @calories.select { |calorie| calorie.user_id == current_user.id }) %>
     
          <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/trainings/edit.html.erb
<%= render "shared/first_header" %>
<%= render "shared/header" %>

<h2>トレーニング内容を編集する</h2>

<%= form_with(model: @training, local: true) do |f| %>



  <%= render 'shared/error_messages', model: f.object %>

  <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">トレーニング内容</label>
    <%= f.text_area :training_name, class: "form-control", id: "exampleFormControlInput1" %>
  </div>

  <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">重量</label>
    <%= f.text_field :weight, class: "form-control", id: "exampleFormControlInput1" %><span>kg
</span> 
 </div>

  <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">回数</label>
    <%= f.text_field :number, class: "form-control", id: "exampleFormControlInput1" %><span>回
    </span> 
  </div>

  <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">日付</label>
    <%= f.datetime_select :start_time, class: "form-control", id: "exampleFormControlInput1" %>
  </div>

<div class="d-grid gap-2">
<%= f.submit "更新する", class: "btn btn-primary" %>
<%= link_to "戻る", :back, class: "btn btn-primary"%>
</div>
<% end %>

<%= render "shared/footer" %>

app/views/trainings/index.html.erb
<%= render "shared/first_header" %>
<%= render "shared/header" %>


<div class="main">
<% if user_signed_in? %>
<%= link_to "トレーニング記録をつける", new_training_path, class: "btn btn-outline-secondary" %>
<%= link_to "摂取カロリー記録をつける", new_calory_path, class: "btn btn-outline-secondary" %>



  <%= month_calendar(events: @trainings, calories: @calories) do |date, trainings, calories| %>

    <% end %>
<% end %>
</div>


<%= render "shared/footer" %>

app/views/trainings/new.html.erb
<%= render "shared/first_header" %>
<%= render "shared/header" %>

<div class="trainings-main">
    <h2 class="trainings-title">トレーニング内容を記録</h2>
    <%= form_with(model: @training, local: true) do |f| %>

      <%= render 'shared/error_messages', model: f.object %>


      <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">*必須* トレーニング名</label>
       <%= f.text_area :training_name, class: "form-control", id: "exampleFormControlInput1", placeholder:"トレーニング名（必須 40文字まで)" ,maxlength:"40" %>
       </div>
  

      <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">*必須* 重量</label>
       <%= f.text_field :weight, class: "form-control", id: "exampleFormControlInput1", placeholder:"重量" ,rows:"7" ,maxlength:"1000" %> <span>kg</script>
       </div>
      
    
      <div class="mb-3">
     <label for="exampleFormControlInput1" class="form-label">*必須* 回数</label>
      <%= f.text_field :number, class: "form-control", id: "exampleFormControlInput1", placeholder:"回数" ,rows:"7" ,maxlength:"1000" %>
      <span>回</script>
      </div>


      <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">*日付</label>
      <div>
     <%= f.datetime_select :start_time, class: "form-control", id: "exampleFormControlInput1" %>
     </div>
     </div>

     <div class="d-grid gap-2">
     <%= f.submit "記録する", class: "btn btn-primary" %>
     <%= link_to '戻る', root_path, class: "btn btn-primary" %>
   </div>
 <% end %>
</div>

<%= render "shared/footer" %>

app/views/trainings/show.html.erb
<%= render "shared/first_header" %>
<%= render "shared/header" %>

<h2>トレーニング内容</h2>

<table class="table">
  <thead>
 
  </thead>
  <tbody>
    <tr>

      <td>トレーニング名</td>
      <td><%= @training .training_name %></td>
    </tr>
    <tr>
 
      <td>重量</td>
      <td><%= @training.weight %> <span>kg</script></td>
    </tr>
    <tr>

      <td>回数</td>
      <td><%= @training.number %><span>回</span></td>
    </tr>

    <td>日付</td>
    <td><%= @training.start_time.strftime("%m-%d") %></td>
  </tr>


  </tbody>
</table>



<div class="d-grid gap-2">
<%= link_to '編集', edit_training_path(@training), class: "btn btn-primary" %>
<%= link_to '消去',training_path(@training.id), class: "btn btn-primary", method: :delete, data: { confirm: '本当に?' } %>
<%= link_to '戻る', trainings_path, class: "btn btn-primary" %>
</div>
</div>

<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/first_header" %>
<%= render "shared/header" %>

<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの情報"%>
      </h2>

      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= "#{@user.nickname}" %></td>
          </tr>
          <tr>
            <th class="table__col1">メールアドレス</th>
            <td class="table__col2"><%= "#{@user.email}" %></td>
          </tr>
          <tr>
            <th class="table__col1">体重</th>
            <td class="table__col2"><%= "#{@user.body_weight}" %><span>kg</script></td>
          </tr>
          <tr>
            <th class="table__col1">身長</th>
            <td class="table__col2"><%= "#{@user.height}" %><span>cm</script></td>
          </tr>
        </tbody>
      </table>

      <script>
      function calc() {
        let weight = document.getElementById("weight").value;
        let height = document.getElementById("height").value;
        let num = weight/( (height/100)*(height/100) );
        let bmi = Math.ceil(num) ;
        
        if (bmi < 18.5) {
                document.getElementById("yase").textContent = "痩せ";
            } else if (bmi >= 25) {
                document.getElementById("himan").textContent = "肥満";
            } else if (bmi >= 18.6 && bmi < 25) {
                document.getElementById("hyojyun").textContent = "標準";
            }

       document.getElementById("bmi").textContent = bmi;
          }
      </script>

      <body>
      <p><b>BMIを計算しよう！</b></p>
      <div class="row">
       <div class="col">
      <div>体重<input type="number" id="weight" value="" class="form-control" >kg</div> 
      <div>身長 <input type="number" id="height" value="" class="form-control" >cm</div> 
      <div><button type="button" onclick="calc()" class="btn btn-primary btn-lg">計算する</button></div> 
      <div><b>あなたのBMI=</span><span id="bmi"></span><span></b></span>
      <p><span><b>判定→</span><span id="yase"><span id="himan"><span id="hyojyun"></span></b></p>
       </div>
      </div>
      </body>
    
      <div class="d-grid gap-2">
      <%= link_to '編集', edit_user_registration_path(@user), class: "btn btn-primary" %> 
      <%= link_to '戻る', root_path, class: "btn btn-primary"%>
      </div>

    </div>
  </div>
</div>

<%= render "shared/footer" %>